language: node_js

node_js:
  - 8.11.1

env:
  - JWTKEY = 'mylastsaver'
  - JWT_TEST_ADMIN = ''
  - JWT_TEST_USER = ''
  
cache:
  directories:
    - node_modules

  services:
  - postgresql

before_script: 
  - npm install
  - psql -c 'create database travis_ci_test;' -U postgres
  - npm run resetdb

script:
- NODE_ENV=test npm run test

after_success: npm run coverage