language: node_js

node_js:
  - 8.11.1

cache:
  directories:
    - node_modules

  services:
  - postgresql

before_script: 
  - npm install
  - npm run resetdb

script:
- npm run test

after_success: npm run coverage